### ISSUE TITLE
/v1/Account/Login

### ISSUE THREAD

**Issue by timtlm** [ZekeSnider/NintendoSwitchRESTAPI#2] opened 2017-08-29 13:55 UTC
I could not get this request to work.  I kept getting Bad Request responses.  I ended up being able to get the access token by using /v1/Account/GetToken using the same request format.

**Comment by Virepri** [comment] 2017-10-07 18:45
https://twitter.com/mattisenhower/status/908460571191795713

this is currently broken. We have no clue how to fix this. If you want to access the Splatoon 2 APIs, you'd best extract your iksm session from the integration by using something like Telerik Fiddler

**Comment by frozenpandaman** [comment] 2018-09-18 12:04
Update at https://github.com/ZekeSnider/NintendoSwitchRESTAPI/issues/6#issuecomment-422365655
(duplicate issues, pretty much)

**Comment by ZekeSnider** [comment] 2018-09-25 07:28
Closing this as duplicate of #6.

**Closed by ZekeSnider** 2018-09-25 07:28 UTC
